
---
title: "Publications"
output: 
  html_document:
    toc: false
    toc_float: false
    includes:
      after_body: footer.html
---


<font size="3"> 

<br>

## Published Papers

**Zee, K. S.**, & Bolger, N. (2022). Physiological coregulation during social support interactions. *Emotion*. [Preprint](https://psyarxiv.com/83hpa){target="_blank"}. [(Datasets & R Code)](https://github.com/kzee/zee-bolger-coreg){target="_blank"}

^+^Paek, J., **Zee, K. S.**, & Higgins, E. T. (in preparation). *Congratulations, so happy for you! Motivation predicts social support for positive events.* \
^+^*Undergraduate mentee*

**Zee, K. S.**, Bolger, N., & Higgins, E. T. (2020). [Regulatory effectiveness of social support](http://dx.doi.org/10.1037/pspi0000235){target="_blank"}. *Journal of Personality and Social Psychology.* [(Datasets & R Code)](https://github.com/kzee/zee-res){target="_blank"} \
*Winner: Graduate Student Paper Award, Relationship Researchers Interest Group, SPSP*

Rossignac-Milon, M., Bolger, N., **Zee, K. S.**, Boothby, E., Higgins, E. T. (2020). [Merged minds: Generalized shared reality in dyadic relationships](https://psycnet.apa.org/record/2020-51514-001){target="_blank"}. *Journal of Personality and Social Psychology.*

Uchino, B. N., Landvatter, J., **Zee, K. S.**, & Bolger N. (2020). [Social support and antibody responses to vaccination:A meta-analysis](https://academic.oup.com/abm/advance-article/doi/10.1093/abm/kaaa029/5838063){target="_blank"}. *Annals of Behavioral Medicine.*

**Zee, K. S.**, & Bolger, N. (2020). [Using coupled oscillators to examine physiological coregulation during social support interactions](https://doi.org/10.1080/00273171.2019.1699392){target="_blank"}. *Multivariate Behavioral Research, 55,* 157-158. 

**Zee, K. S.**, & Kumashiro, M. (2019). [Investigating mechanisms of social support effectiveness: The case of locomotion motivation](https://onlinelibrary.wiley.com/doi/epdf/10.1111/pere.12298){target="_blank"}. *Personal Relationships, 26,* 654–679.

**Zee, K. S.**, & Weiss, D. (2019). [High-quality relationships strengthen the benefits of a younger subjective age across adulthood](http://dx.doi.org/10.1037/pag0000349){target="_blank"}. *Psychology and Aging, 34,* 374–388. [(Datasets & R Code)](https://github.com/kzee/zee-weiss-2019){target="_blank"}

Bolger, N., & **Zee, K. S.** (2019). [Heterogeneity in temporal processes: Implications for theories in health psychology](https://onlinelibrary.wiley.com/doi/full/10.1111/aphw.12159){target="_blank"}. *Applied Psychology: Health & Well-being, 11,* 198-201.

**Zee, K. S.**, & Bolger, N. (2019). [Visible and invisible social support: How, why, and when](https://doi.org/10.1177/0963721419835214){target="_blank"}. *Current Directions in Psychological Science, 28*, 314-320. 

Bolger, N., **Zee, K. S.**, Rossignac-Milon, M., & Hassin, R. R. (2019). [Causal processes in psychology are heterogeneous](http://dx.doi.org/10.1037/xge0000558){target="_blank"}. *Journal of Experimental Psychology: General*, *148*, 601-618. [(Datasets & R Code)](https://github.com/kzee/heterogeneityproject){target="_blank"}

**Zee, K. S.**, Cavallo, J. V., Flores, A. J., Bolger, N., & Higgins, E. T. (2018). [Motivation moderates the effects of social support visibility](http://dx.doi.org/10.1037/pspi0000119){target="_blank"}. *Journal of Personality and Social Psychology, 114*, 735-765. \
*Winner: Graduate Student Paper Award, Relationship Researchers Interest Group, SPSP*

Cavallo, J. V., **Zee, K. S.**, Higgins, E. T. (2016). [Giving what is needed: Regulatory mode orientations and social support provision](https://doi.org/10.1177%2F0146167216651852){target="_blank"}. *Personality and Social Psychology Bulletin, 42*, 1111-1128. 


<br>



## Papers in Preparation (Selected)

**Zee, K. S.**, & Bolger, N. (in preparation). *Heterogeneity in dyadic interaction and implications for self-regulation.*

**Zee, K. S.**, & Bolger, N. (in preparation). *Increasing precision in meta-analytic estimates by modeling variability due to outcomes.*  



</font> 

 <a href="#top">Back to top</a>