
---
title: "Research"
output: 
  html_document:
    toc: false
    toc_float: false
    includes:
      after_body: footer.html
---

<font size="3"> 

<br>

### Overview
My research investigates how and why social relationships benefit well-being. My work is driven by three questions. First, how do relationship partners support each other effectively in times of difficulty? Second, what role do relationship partners play in fostering effective self-regulation across the lifespan? And third, how do partners within a dyad regulate as a unit? To answer these questions, my work synthesizes literatures on close relationships, self-regulation, and lifespan development in novel ways, spans multiple levels of analysis, and uses a range of methods, including experiments, psychophysiology, and daily diaries. In my empirical work, I draw on and develop the best statistical methods available to address my theoretical aims. 

<br>

### Social Support Effectiveness
Although it is often assumed that social support (practical and emotional help from others) underlies the health-promoting effects of relationships, empirical evidence for this assumption has been mixed. Receiving support has sometimes been linked to reduced stress and lower mortality risk, suggesting that, if given appropriately, support may enable people to live longer, healthier lives. However, receiving support can also undermine recipients’ feelings of competence and worsen their distress. I have integrated theories of self-regulation and motivation to reconcile these mixed findings on the costs and benefits of support. Building on theories positing that effective support must address recipients’ needs, I have tackled the notion of addressing recipients’ needs in a novel way by proposing that support is most effective when it addresses recipients’ *self-regulatory* needs (Zee et al., 2018; Zee, Bolger, & Higgins, under review; Zee & Kumashiro, in press; Cavallo, Zee, & Higgins, 2016, in preparation).

In [one project](https://psycnet.apa.org/fulltext/2018-03575-001.html){target="_blank"}, I found that recipients who received support given in a manner (*visible* vs. *invisible*; [Zee & Bolger, 2019](https://doi.org/10.1177/0963721419835214){target="_blank"}) that matched their self-regulatory orientation felt less distressed, experienced higher self-efficacy, and showed tempered cardiovascular reactivity during a laboratory stressor. 

In [subsequent research](https://psyarxiv.com/h2mrv){target="_blank"}, I developed a new construct to directly assess the degree to which social support is attuned to recipients’ self-regulatory needs. I found that receiving support that better addressed recipients' self-regulatory needs was linked to outcomes that are important for effective self-regulation, such as lower negative mood, greater motivation to persist on a demanding task, and tempered cardiovascular stress. Moreover, receiving support that addressed their self-regulatory needs was linked to greater motivation to perform well on a stressful speech, which in turn predicted better objective speech performance. 

<br>

### Social Relationships across the Lifespan
My research on social relationships and social support also extends to a lifespan context and examines the role of social relationships in promoting healthy aging. In [one investigation](https://psycnet.apa.org/fulltext/2019-25483-003.html){target="_blank"}, I found that although feeling younger than one's chronological age (a younger subjective age bias) is known to be associated with health benefits over time, the positive effects of a younger subjective bias are intesified among individuals in higher (vs. lower) quality marital relationships. 

In a second project, I am currently examining older couples' dyadic support interactions leading up to a laboratory stressor, in order to examine the effects of support behaviors in mitigating stress reactivity in older adulthood and illuminate how older adults’ support interactions differ from those of younger adults.   

<br>

### Co-Regulation and Dyad as Unit of Analysis
In an additional stream of research, I examine dyad-level co-regulation. Co-regulation is a process in which changes in one person’s emotional or physiological state are dynamically influenced by both their own prior state and their partner’s state. My research examines when such co-regulatory processes become activated and what implications they have for individuals’ well-being. 

<br>


### Statistical Methods
I develop and implement novel statistical methods to better address my research aims on interpersonal relationships and regulatory processes. First, my work involves modeling and interpreting between-subject heterogeneity in experimental and non-experimental effects. Between-subject heterogeneity refers to the notion that subjects differ in the extent to which they show a "typical" effect; some may show especially strong effects, whereas others may show weak effects or even a reversal in the direction of their effect. In [one project](https://psycnet.apa.org/fulltext/2019-19962-002.html){target="_blank"}, my colleagues and I proposed the importance of working from the assumption that causal processes are heterogeneous and highlighted the utility of multilevel modeling (in particular, random effects) for examining heterogeneity directly. We revealed that noteworthy between-subject heterogeneity is often present, even in tightly controlled experiments. I have also used random effects to examine sources of heterogeneity beyond subject-level heterogeneity. For example, I have developed a way of [summarizing complex results across outcomes and datasets](https://psyarxiv.com/h2mrv){target="_blank"} by treating the outcomes and datasets as crossed random effects, while also assessing the degree of heterogeneity in both influences. 

Second, I combine dyadic analyses and time series analyses to model temporal dynamics in interpersonal processes. Much of my work in this area has focused on dynamical systems modeling. These models offer valuable insight into temporal processes by capturing the rate of change (velocity) and speed of change (acceleration) in individuals’ or dyads’ responses, and into regulatory processes by capturing fluctuations around an equilibrium level. I have used these models to study co-regulatory dynamics during couples’ laboratory discussions. 

<br>

</font> 