
---
title: "Teaching"
output:
  html_document:
    includes:
      after_body: footer.html
    toc: no
    toc_float: no
---


<font size="3"> 

<br>


## Statistics Teaching


<br>

#### [APA Advanced Training Institute](https://www.apa.org/science/resources/ati/){target="_blank"}: [Intensive Longitudinal Data Analysis](https://longitudinalresearchinstitute.com/){target="_blank"} <br>
- Role: Lab Instructor <br>
- Level: Graduate/Professional (PhD students and faculty in social science disciplines) <br>
- Lead Instructors: Drs. Nilam Ram, Kevin Grimm, Niall Bolger, & Jean-Philippe Laurenceau
- Labs Taught: Generalized Multilevel Modeling, Moderated 1-1-1 Within-Person Mediation Analysis <br>
<br>
<br>


#### Introduction to Statistical Modeling in Psychology (graduate course), Columbia University, 2019 <br>
- Role: Teaching Assistant with weekly 2-hr lab taught in R <br>
- Level: Graduate (PhD students in Psychology) <br>
- Supervisor: Niall Bolger <br>
- Evaluation: Mean = 5.0/5, Median = 5.0/5
<br>
<br>

#### Analysis of Change (graduate course on multilevel modeling), Columbia University <br>
- Role: Teaching Assistant with weekly 2-hr lab taught in R <br>
- Level: Graduate (PhD students in Psychology and Management) <br>
- Supervisor: Niall Bolger <br>
- Evaluation: Mean = 4.6/5, Median = 5.0/5 
<br>
<br>

#### Psychophysiological Methods & Analysis (graduate course), Columbia University <br>
- Role: Guest Lecturer, "Dyadic Psychophysiological Methods & Analysis" 
<br>
<br>

#### Psychophysiological Methods & Analysis (graduate course), Columbia University <br>
- Role: Teaching Assistant with weekly 2-hr lab <br>
- Level: Graduate (PhD students in Psychology and Management) <br>
- Supervisor: Niall Bolger <br>
- Evaluation: Mean = 5.0/5, Median = 5.0/5 
<br>
<br>


<br>

## Management Teaching
<br>

#### Leadership in Organizations, London Business School <br>
- Role: Teaching Assistant 
- Level: Graduate (Masters in Management students)
- Supervisor: Dr. Xi Zou

<br>
<br>

## Psychology Teaching  

<br>

#### Stress in an Interpersonal Context (advanced undergraduate seminar), Columbia University <br>
- Role: Instructor of Record. Developed course and designed syllabus. <br>
- Level: Undergraduate (advanced seminar) <br>
- *Note: Teaching evaluations were not collected due to COVID-19 outbreak*
<br>
<br>


#### Social Psychology, Barnard College <br>
- Role: Grader <br>
- Level: Undergraduate <br>
- Supervisor: Dr. Colin Leach <br>
- Guest Lecture: "Interpersonal Relationships" 
<br>
<br>

#### Introduction to Social Cognition, Columbia University <br>
- Role: Guest Lecturer, "Social Support and Emotion" 
<br>
<br>

#### Research Methods: Social Cognition and Emotion, Columbia University <br>
- Role: Teaching Assistant with weekly 2-hr lab (5 sections over 3 semesters) <br>
- Level: Undergraduate <br>
- Supervisor: Dr. Kevin Ochsner <br>
- 2015 Evaluation: Mean = 4.7/5, Median = 5.0/5 <br>
- 2016 Evaluation: Mean = 4.2/5, Median = 5.0/5 <br> 
- 2017 Evaluation: Mean = 4.8/5, Median = 5.0/5 
<br>
<br>

#### The Science of Psychology, Columbia University <br>
- Role: Teaching Assistant <br>
- Level: Undergraduate <br>
- Guest Lecture: "Attachment Across the Lifespan" <br>
- Supervisor: Patricia Lindemann <br>
- Evaluation: Mean = 4.2/5, Median = 4.0/5 
<br>
<br>


#### General Foundations of Psychology, Birkbeck, University of London <br>
- Role: Seminar Leader (led weekly 2-hr seminar, 2 sections over 2 terms) <br>
- Level: Undergraduate <br>
- Supervisor: Simon Green
<br>
<br>

<br>


## Mentoring

I have supervised and mentored over 40 undergraduate and post-bac research assistants and honors students since 2014. My students have been recognized with awards from Columbia University as well as international societies, such as the Society for Personality and Social Psychology, and many have continued on to doctoral programs in psychology and related fields. 
<br>
For my teaching and mentoring effectiveness, I received Columbia University's [Presidential Award for Outstanding Teaching](https://provost.columbia.edu/content/presidential-teaching-awards){target="_blank"} in 2019. 


<br>
<br>



</font> 

 <a href="#top">Back to top</a>